services:
  # financial-api:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.dev
  #   container_name: financial-api
  #   environment:
  #     DB_HOST: ${DB_HOST:-localhost}
  #     DB_PORT: ${DB_PORT:-3306}
  #     DB_USER: ${DB_USER:-dev_user}
  #     DB_PASSWORD: ${DB_PASSWORD:-dev_password}
  #     DB_NAME: ${DB_NAME:-financial_db_dev}
  #   ports:
  #     - "${API_PORT:-8000}:${API_PORT:-8000}"
  #   depends_on:
  #     - db
  #   networks:
  #     - financial-network
  #   env_file:
  #     - ./app/.env.dev

  db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-rootpassword}
      MYSQL_DATABASE: ${DB_NAME:-financial_db_dev}
      MYSQL_USER: ${DB_USER:-dev_user}
      MYSQL_PASSWORD: ${DB_PASSWORD:-dev_password}
    ports:
      - "${DB_PORT:-3306}:${DB_PORT:-3306}"
    restart: always
    networks:
      - financial-network
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_bin --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql_data:/var/lib/mysql
    env_file:
      - ./app/.env.dev
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--host", "localhost"]
      interval: 30s
      retries: 3
      start_period: 5s
      timeout: 5s

networks:
  financial-network:
    driver: bridge

volumes:
  mysql_data:
    driver: local
