version: '3.8'

services:
  app:
    build: .
    environment:
      - ENV=development
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    # Para produção, use:
    # command: gunicorn -w 4 main:app --host 0.0.0.0 --port 8000